version: "3.8"
services:
  db:
    image: postgres:12
    # restart: always
    container_name: postgres-for-cfc
    environment:
      POSTGRES_DB: cfc
      POSTGRES_PASSWORD: ola
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    # networks:-
    ports:
      - 5432:5432

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ola-server
    depends_on:
      - db
    # restart: always
    container_name: cfc-backend
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_DATABASE: postgres
      DB_PASSWORD: ola
    # volumes:- 
    # networks:
    ports:
      - 3000:3000

  frontend:
    build:
      context: ./frontend/cfc
      dockerfile: Dockerfile
    image:
    container_name:
    volumes:
      -*********
    networks:
    ports:
      - 8080:8080
  
volumes:
  pgdata: